### ISSUE TITLE
npm compile error building docker image as outlined in the ReadMe/ApplicationSetup

### ISSUE THREAD

**Issue by zsiddiqi** [ustwo/react-project-base#2] opened 2015-12-16 14:43 UTC
Hi,

I was trying to setup the base project on my machine running Ubuntu and am running into issues. While following the section ApplicationSetup https://github.com/ustwo/react-project-base/blob/master/readme.md#application-setup, I get the following error when the "t build" command is executed:

```
root@41ce1742da3a:/home/app# npm run-script compile
npm info it worked if it ends with ok
npm info using npm@2.7.5
npm info using node@v1.6.4
npm info precompile react-project-base@0.0.1
npm info compile react-project-base@0.0.1

> react-project-base@0.0.1 compile /home/app
> browserify -d -x react -x react/addons -x classnames -x moment src/index.jsx -o public/index.js && echo "Compiled"

Error: Cannot find module 'lodash/object/set' from '/home/app/src/flux'
    at /home/app/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/app/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/app/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/app/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/app/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/app/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:77:15)

npm info react-project-base@0.0.1 Failed to exec compile script
npm ERR! Linux 3.19.0-28-generic
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "run-script" "compile"
npm ERR! node v1.6.4
npm ERR! npm  v2.7.5
npm ERR! code ELIFECYCLE
npm ERR! react-project-base@0.0.1 compile: `browserify -d -x react -x react/addons -x classnames -x moment src/index.jsx -o public/index.js && echo "Compiled"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-project-base@0.0.1 compile script 'browserify -d -x react -x react/addons -x classnames -x moment src/index.jsx -o public/index.js && echo "Compiled"'.
npm ERR! This is most likely a problem with the react-project-base package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     browserify -d -x react -x react/addons -x classnames -x moment src/index.jsx -o public/index.js && echo "Compiled"
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-project-base
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/app/npm-debug.log
```

Any help would be much appreciated. Thanks!

**Comment by ch2ch3** [comment] 2015-12-18 16:22
Hi @zsiddiqi, thanks for checking out our project! It seems the problem is on our end, the version of `lodash` specified in `package.json` is outdated and does not include `set`. I'll push a fix for this in a bit.

**Closed** 2015-12-18 16:27 UTC
